timesBr = ('Palmeiras', 'Flamengo', 'Fluminense', 'Athletico-PR', 'Bragantino', 'Bahia', 'Coritiba', 'São Paulo', 'Atlético-MG', 'Corinthians', 'Cruzeiro', 'Botafogo', 'Vitória', 'Internacional', 'Santos', 'Grêmio', 'Vasco', 'Remo', 'Mirassol', 'Chapecoense')
print('-='*40)
print(f'Lista de times do Brasileirão: {timesBr}')
print('-='*40)
print(f'Os 5 primeiros colocados são {timesBr[:5]}')
print('-='*40)
print(f'Os últimos quatro são {timesBr[16:21]}')
print('-='*40)
print(f'Times em ordem alfabética são {sorted(timesBr)}')
print('-='*40)
print(f'A {timesBr[-1]} está na {timesBr.index('Chapecoense')+1}ª posição')